### ISSUE TITLE
(suggestion) hidden when you are breaking a block

### ISSUE THREAD

**Issue by EternalOne11** [3TUSK/PlacementPreview#3]
Could you make it so the placement overlay is hidden when you are breaking a block or swinging a weapon and add the overlay to a block when you have a block in your off-hand?

**Comment by 3TUSK** [comment]
I will see what I can do.
~~Also is it possible to place block using your off-hand?~~ TIL you can.

**Comment by 3TUSK** [comment]
1.3.0 is now available at https://github.com/3TUSK/PlacementPreview/releases/tag/1.3.0
Before CurseForge approves it, you can get the new version here. Let me know if the auto-hide feature works, so that I can close this ticket.

---

CurseForge: https://www.curseforge.com/minecraft/mc-mods/place-preview/files/2975672

**Comment by 3TUSK** [comment]
In case you have other issues, please open a new ticket. Gonna close this one for now.
